default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
  password: postgres

development:
  <<: *default
  database: mpa_ibagems_development

test:
  <<: *default
  database: mpa_ibagems_test

production:
  <<: *default
  database: mpa_ibagems_production
  username: mpa_ibagems
  password: <%= ENV["MPA_IBAGEMS_DATABASE_PASSWORD"] %>
